### ISSUE TITLE
Using merged topic IMU instead of accel and gyro

### ISSUE THREAD

**Issue by Shervina-lim** [berndpfrommer/basalt_ros1#4]
Hi,

I'm interested in using structure core colour camera instead of t265 that you used for basalt. The issue is that the structure core only publishes a single IMU topic instead of accel and gyro like t265.

So, is it possible to use a single IMU topic for basalt?

**Comment by berndpfrommer** [comment]
Yes, there is support for that (not sure I tested it though). If you specify a single topic in your launch file like so:
`<rosparam param="imu_topics">["imu"]</rosparam>`
And then remap the "imu" topic to your imu source, that should work.

**Comment by Shervina-lim** [comment]
Thanks for the prompt reply! 

I merged the accel and gyro topic to one IMU for the t265 and modify the launch file but I got this error when I run it:
![imu_error](https://user-images.githubusercontent.com/58497215/106109939-107b6900-6185-11eb-8623-7ff56f58c75a.png)

I got the same error when running stucture core with basalt too!

Do you know how to solve this issue?

Another question: Structure core camera uses another distortion model,  plumb_bob. Does basalt support this distortion model?

**Comment by berndpfrommer** [comment]
- check that you are subscribed to the right image topics and make sure they actually have data.
- how is your CPU load? I've seen these error messages before when the front-end could not keep up with processing the frames.
I'd have to check the code to see what distortion models basalt supports, don't know of the top of my head. I only ever ran it with fisheye cameras.

**Comment by Shervina-lim** [comment]
Hi, 

1. check that you are subscribed to the right image topics and make sure they actually have data.

I've checked both and its correct 

2. how is your CPU load?

CPU load quite low and I managed to run it basalt with **accel** and **gyro** so, I don't think this is a problem. I've attached a screen shot for your reference. 
![cpu_load](https://user-images.githubusercontent.com/58497215/106546821-fd7ee500-6546-11eb-98e9-010d50fa938d.png)

If Basalt does not support **plumb_bob**, can I still run basalt with structure core?

**Comment by berndpfrommer** [comment]
Could you please make a *very short* rosbag that reproduces the issue and upload a link to it on e.g. google drive? I will have a look at it.
I checked the basalt code base and incredibly I could not find a plumb_bob implementation there. All kinds of other cameras, but not plumb_bob. Maybe I missed it. Please ask the original basalt authors about it.
About the structure core: I couldn't find documentation for the distortion model either (didn't look to hard), but just looking at the images, the grey camera is definitely fisheye. The color is probably not. Unless basalt does indeed support plumb_bob this leaves you with the painful option of running a separate ROS node to undistort the image before feeding it into basalt. In this case you need to specify a different camera in the calib file, I think "pinhole" is the right one. Make sure to use the focal lengths *after* undistortion. BTW the camera models can be found in the header files in basalt/thirdparty/basalt-headers/include/basalt/camera. There's also a chance that the color camera already publishes fully rectified images, in which case pinhole should work. You could verify that by doing a calibration and checking that the distortion coefficients are very small.
Another remark: there is a reason why people use wide angle lenses for odom. Your results with the color camera will not be as good.

**Comment by Shervina-lim** [comment]
Hi,

Sure. I will uploaded the t265 rosbag in this [link](https://drive.google.com/drive/folders/1ywAjLGYtbFgbL63AQp9n4vNKAEr0k78C?usp=sharing).

Regarding the plumb_bob model, I got them from the camera info topic published by their ros driver. I will uploaded the camera parameters from the driver to the google drive for your reference. 

- BTW the camera models can be found in the header files in basalt/thirdparty/basalt-headers/include/basalt/camera. 

Ok. I'll check them out. Thanks!

- Another remark: there is a reason why people use wide angle lenses for odom. Your results with the color camera will not be as good. 

Ah I understand. Originally, I wanted to use the colour camera for this as I thought that the grey camera may not produce good results as it noisy. Please refer to the attached image. Do you think that the grey cameras would be suitable for this application?

![sc_images](https://user-images.githubusercontent.com/58497215/106703368-14940480-6625-11eb-95c9-65bde9717bbc.png)

**Comment by berndpfrommer** [comment]
I'm a bit confused. What you are showing as grey image is not the wide angle view that I can see on structure's website. This is probably the IR image from the depth sensor. The graininess is the structured light. And no, these images are not useful for VIO.

As to why you can't get basalt to work:
- the T265 bag has bad time stamps in the header msgs. The images are not synchronized:
```
left camera:
---
seq: 629
stamp: 
  secs: 1612336117
  nsecs: 978378487
frame_id: "t265_fisheye1_optical_frame"
---
seq: 630
stamp: 
  secs: 1612336118
  nsecs:  11607155
frame_id: "t265_fisheye1_optical_frame"
---
seq: 631
stamp: 
  secs: 1612336118
  nsecs:  44937733
frame_id: "t265_fisheye1_optical_frame"
---
```
```
right camera:
---
seq: 629
stamp: 
  secs: 1612336117
  nsecs: 980539273
frame_id: "t265_fisheye2_optical_frame"
---
seq: 630
stamp: 
  secs: 1612336118
  nsecs:  13686990
frame_id: "t265_fisheye2_optical_frame"
---
seq: 631
stamp: 
  secs: 1612336118
  nsecs:  47068397
frame_id: "t265_fisheye2_optical_frame"
---

```

Probably some setting with the T265 ROS driver is off. There is a flag "enable_sync" that sounds like it could be important.

- the structure core bag has synchronized images, but they are the grainy ones from above. When I feed them into basalt it crashes right away with an SO3 error. Why that is I don't know. Probably the optimizer bombs out because the visual data is bad. This is not going to work. The color camera is monocular from what I see, so that won't help because basalt requires stereo.

If you want to work with this camera you either go with an RGB-D based odom package, or get the fisheye gray camera version.
